# Generated by Django 3.0.1 on 2020-06-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.CharField(choices=[('PG TRB', 'PG TRB'), ('POLY TRB', 'POLY TRB'), ('ENGG TRB', 'ENGG TRB'), ('TNSET', 'TNSET'), ('UG TRB', 'UG TRB'), ('SAMPLE MATERIALS', 'SAMPLE MATERIALS'), ('ARCHIVES', 'ARCHIVES')], max_length=100),
        ),
    ]
