# Generated by Django 2.2 on 2019-12-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('PG TRB', 'PG TRB'), ('POLY TRB', 'POLY TRB'), ('ENGG TRB', 'ENGG TRB'), ('TNSET', 'TNSET'), ('UG TRB', 'UG TRB'), ('SAMPLE MATERIALS', 'SAMPLE MATERIALS'), ('ARCHIVES', 'ARCHIVES')], max_length=255),
        ),
    ]
