# Generated by Django 2.2 on 2019-12-26 14:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191226_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tagline', models.TextField(max_length=256)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
