# Generated by Django 2.2 on 2019-12-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_pagedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinators', models.TextField(max_length=500)),
                ('address', models.TextField(max_length=500)),
            ],
        ),
    ]
