# Generated by Django 2.2 on 2019-12-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
