# Generated by Django 2.2 on 2019-12-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_website_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='image',
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
